const PRD="# 系统设置—站点显示配置迭代\n\n## 已确认内容\n在 DD.GG「系统管理 → 系统设置 → 站点显示配置」中加入以下四项，后台风格依据图9，客户端位置依据图2、4、6、8。\n\n| 配置 | 参考图可见功能 | 客户端对应位置 |\n|---|---|---|\n| 游戏合作平台 | 默认/自定义、图片预览、上传图片、确定；JPG/PNG/SVG，建议1125×744；图片不超过2M | 首页底部游戏合作平台区域 |\n| 充值合作伙伴 | 默认/自定义、图片预览、确定；建议1125×195；图片不超过2M | 游戏合作平台下方 |\n| 首页底部文案 | 多行文本、保存 | 品牌版权区域下方 |\n| 主媒体配置 | 序号、媒体类型、图标、媒体链接、备注、操作；新增、编辑、删除；图标建议114×114；图片不超过2M | 底部文案下方 |\n\n## 业务目标与流程\n统一维护首页底部展示素材和媒体入口，减少客户端逐项修改。操作路径：进入配置 → 修改草稿 → 校验 → 保存成功 → 客户端读取已保存配置。客户端展示顺序：游戏合作平台 → 充值合作伙伴 → 品牌版权 → 底部文案 → 主媒体图标。\n\n## 配置规则\n| 场景 | 原型行为 |\n|---|---|\n| 保存与重新读取 | 点击“确定”或“保存”并通过校验后保存配置；编辑不影响已保存客户端；不提供“取消修改”按钮；未保存时切换栏目或刷新页面，直接丢弃草稿并重新读取已保存配置，不弹出确认提示 |\n| 默认图片 | 内置文字标识示意图，仅演示版式，正式品牌素材待提供 |\n| 默认与自定义切换 | 切回默认并保存后，保留已保存的自定义图片；再次选择自定义时回显，仅上传新图片并确定保存后替换原图；未保存的替换不生效 |\n| 自定义图片 | 两类合作伙伴均使用一张组合图；JPG/PNG/SVG；游戏合作平台建议1125×744；充值合作伙伴建议1125×195；单张图片不超过2M；按比例缩放 |\n| 图片校验 | 所有上传图片统一限制不超过2M，等于2M允许上传，超过2M拒绝并保留原草稿；建议尺寸不作为强制拦截条件；自定义必须上传可解码图片；不合并或新增实际支付渠道/游戏接入关系 |\n| 文案 | 纯文本，保留换行，演示上限3000字；允许清空并隐藏文案区域 |\n| 媒体新增/编辑 | 媒体类型、图标、链接必填；备注可选；新增时必须上传图标，不提供内置图标选择；编辑时回显已上传图标，未替换则保留；上传图标建议114×114，图片不超过2M；链接允许HTTPS或#；#表示仅展示 |\n| 媒体类型唯一性 | 新增和编辑均不允许与其他记录的媒体类型重复；原型按去除首尾空格且不区分大小写校验，编辑排除当前记录 |\n| 媒体弹窗 | 按顺序展示媒体类型输入框、媒体链接输入框、图标预览及上传图片按钮、备注多行文本框；底部“确定”保存，右上角关闭不保存 |\n| 媒体删除 | 二次确认；取消不变；确认后客户端移除；列表为空则隐藏图标区域 |\n| 媒体排序 | 按新增顺序展示，编辑保持原位置，删除后序号重排；本期不擅自加入启停/拖动排序 |\n| 外链 | 有效HTTPS在新页打开；演示数据全部为#，正式链接待提供 |\n| 持久化 | 同一页面内联动；通过同源HTTP打开时支持跨标签页同步；直接双击文件时跨页存储因浏览器而异，以后台内嵌预览为准；存储失败提示，不冒充成功 |\n\n\n## 状态与闭环\n| 状态/操作 | 后台 | 客户端 |\n|---|---|---|\n| 已保存 → 编辑 | 进入未保存状态 | 保持原值 |\n| 草稿 → 切换栏目或刷新页面 | 不保存草稿，不弹出确认提示，重新读取已保存配置 | 不变 |\n| 草稿 → 校验失败 | 显示原因，保留草稿 | 不变 |\n| 草稿 → 保存成功 | 更新配置 | 刷新已保存内容 |\n| 草稿 → 存储失败 | 错误提示，保留草稿 | 不变 |\n| 删除 → 取消/确认 | 保留/删除对应行 | 保留/移除对应图标 |\n\n## 权限地图\n| 模块/页面 | 权限项 | 作用范围 | 无权限表现 |\n|---|---|---|---|\n| 系统管理/站点显示配置 | 查看 | 四项配置 | 页面是否隐藏待确认 |\n| 游戏合作平台、充值合作伙伴、首页底部文案 | 各项独立保存权限 | 对应配置 | 按钮置灰；原型提供只读模拟 |\n| 主媒体配置 | 新增、编辑、删除独立权限 | 媒体条目 | 对应按钮置灰；原型只读模拟统一关闭写入 |\n| 用户日志（新） | 查看日志 | 授权操作记录 | 数据范围待确认 |\n\n## 操作日志\n\n| **操作日志** | **所有增删改操作均需按「用户日志（新）」写入规范记录操作模块、操作页面、操作对象、操作内容、关键词、操作人、操作人类型、操作时间、操作IP等字段。** |\n| :------- | :--------------------------------------------------------------------------- |\n\n## 客户端更新与缓存建议\n保存成功后，客户端接收接口更新通知，获取并更新新内容，更新完成后写入客户端本地缓存。此项仅为实现建议；本地原型仅演示保存联动，不代表已接入真实通知接口。\n";
const KEY='ddgg-site-display-v1';
const names={game:'游戏合作平台',pay:'充值合作伙伴',copy:'首页底部文案',media:'主媒体配置',doc:'需求说明'};
const icons={'18':'18⁺',TG:'➤',WHATSAPP:'◉',Instagram:'◎',Facebook:'f'};
const initial={game:{mode:'default',img:''},pay:{mode:'default',img:''},copy:'[Texto de demonstração — conteúdo oficial pendente]\n\n1. Este produto é destinado a usuários maiores de 18 anos.\n\n2. Jogue com responsabilidade.\n\n3. Consulte os termos e condições da plataforma.',media:Object.keys(icons).map((type,i)=>({id:'media-'+(i+1),type,icon:icons[type],url:'#',note:''}))};
let state=structuredClone(initial),tab='game',draft,dirty=false,readonly=false,loadError=false,uploadVersion=0;
try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.game&&x.pay&&typeof x.copy==='string'&&Array.isArray(x.media))state=x}catch(e){loadError=true}
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3000)}
function logos(k){let a=k==='game'?['PG','Pragmatic','PLAY','NewG','FD','CQ9','BAXO','JDB','TaDa']:['◈ pix','VISA','●●','₮','₿','◇','Q','PayPal','G Pay','Pay'];return `<div class="logogrid ${k==='pay'?'payments':''}">${a.map((v,i)=>`<span style="color:${['#53c9b3','#799ced','#eeaa49','#b8d67e'][i%4]}">${v}</span>`).join('')}</div>`}
function partner(k){return state[k].mode==='custom'&&state[k].img?`<img src="${esc(state[k].img)}" alt="${names[k]}">`:logos(k)}
function iconHtml(m){return m.icon.startsWith('data:image/')?`<img src="${esc(m.icon)}" alt="${esc(m.type)}">`:esc(m.icon)}
function client(){return `<div class="phone"><div class="screen"><div class="clientheader"><span class="ddlogo">DD.GG</span><span class="deposit">Depósito</span></div><div class="gamebar">${['SLOTS','AO VIVO','SPORTS','CASINO'].map((v,i)=>`<div><b>${['♠','♛','⚽','♦'][i]}</b>${v}</div>`).join('')}</div><div class="clientsection"><div class="sectionlabel">Parceiros de jogos</div>${partner('game')}</div><div class="clientsection"><div class="sectionlabel">Parceiros de pagamento</div>${partner('pay')}</div><div class="copyright"><div><span class="ddlogo">DD.GG</span><small>Protótipo de demonstração<br>Identidade visual ilustrativa</small></div><span class="orb">✦</span></div>${state.copy||state.media.length?`<div class="footerbox">${state.copy?`<div class="footercopy">${esc(state.copy)}</div>`:''}<div class="socials">${state.media.map(m=>`<a href="${esc(m.url)}" ${m.url==='#'?'data-placeholder="true"':'target="_blank" rel="noopener noreferrer"'} title="${esc(m.type)}" aria-label="${esc(m.type)}">${iconHtml(m)}</a>`).join('')}</div></div>`:''}<div class="bottomnav">${['Início','Promoção','Convidar','Saque','Perfil'].map((x,i)=>`<div><b>${['⌂','♜','⊕','▣','♙'][i]}</b>${x}</div>`).join('')}</div></div></div>`}
function updatePreview(){const p=$('#clientPreview');if(p)p.innerHTML=client();document.querySelectorAll('[data-placeholder]').forEach(a=>a.onclick=e=>{e.preventDefault();toast('仅展示图标；正式跳转链接待配置')})}
function resetDraft(){draft=structuredClone(state[tab]??null);dirty=false;uploadVersion++}
function mark(){dirty=true;const d=$('#dirty');if(d)d.textContent='有未保存修改'}
function save(value,action='保存',object=names[tab]){if(readonly)return toast('当前为只读演示，无操作权限');const next=structuredClone(state);next[tab]=value;delete next.logs;try{localStorage.setItem(KEY,JSON.stringify(next))}catch(e){toast('保存失败：本地存储不可用或容量不足，草稿已保留');return false}state=next;resetDraft();render();toast('保存成功，客户端已更新');return true}
function render(){if(document.body.dataset.client){$('#root').innerHTML=`<div class="standalone"><p>DD.GG 客户端原型 · 演示素材 <a href="index.html">返回后台</a></p><div id="clientPreview"></div></div>`;updatePreview();return}
$('#root').innerHTML=`<aside><div class="brand">◉ DD.GG</div><div class="navitem">◴ 平台概况</div><div class="navitem group">⚙ 系统管理　⌃</div>${['角色管理','账号管理','系统设置','登录日志','谷歌令牌','域名管理(新)','安全设置','子账号操作日志(新)','马甲包管理','IP白名单'].map(x=>`<div class="navitem sub ${x==='系统设置'?'selected':''}">${x}</div>`).join('')}<div class="navitem">▧ 商户游戏管理</div><div class="navitem">♙ 会员管理</div></aside><main><div class="top"><span>☰　系统管理　/　系统设置</span><span class="tiny">巴西站 · DD.GG　　演示管理员</span></div><div class="top" style="height:40px;justify-content:flex-start"><span class="tag">系统设置　×</span></div><div class="tabs"><span>站点配置</span><span class="active">站点显示配置</span><span>登录注册配置</span><span>公共资源配置</span></div><div class="workspace"><nav class="subnav">${['轮播图配置','营销配置','跑马灯配置','快捷入口'].map(x=>`<button class="old" disabled title="现有功能，本次不展开">${x}</button>`).join('')}${Object.entries(names).map(([k,v])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${v}</button>`).join('')}</nav><section class="content"><div class="toolbar"><div><h1>${names[tab]}</h1><span class="tiny">系统设置 / 站点显示配置</span></div><label class="tiny"><input id="readonly" type="checkbox" ${readonly?'checked':''}> 只读演示</label></div><div class="notice">配置保存后更新右侧客户端，配置规则详见「需求说明」。</div><div id="panel"></div></section><section class="preview"><div class="previewbar"><b>客户端 · 已保存配置</b><a href="client.html" target="_blank">独立打开 ↗</a></div><div id="clientPreview"></div><div class="hint">手机H5展示示意 · 非真实业务数据<br>合作伙伴图标仅为视觉示意，不代表实际接入。</div></section></div></main>`;
$('#readonly').onchange=e=>{readonly=e.target.checked;render()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;readSaved();resetDraft();render()});renderPanel();updatePreview()}
function actions(label='保存'){return `<div class="actions"><button class="primary" id="save" ${readonly?'disabled':''}>${label}</button><span class="dirty" id="dirty">${dirty?'有未保存修改':''}</span></div>`}
function wireActions(){$('#save').onclick=()=>{if((tab==='game'||tab==='pay')&&draft.mode==='custom'&&!draft.img)return toast('请先上传自定义图片');save(draft)}}
function renderPanel(){let p=$('#panel');if(tab==='game'||tab==='pay'){p.innerHTML=`<div class="formrow"><div class="label">${names[tab]}配置</div><div class="radios">${['default','custom'].map((m,i)=>`<label><input type="radio" name="mode" value="${m}" ${draft.mode===m?'checked':''} ${readonly?'disabled':''}> ${i?'自定义':'默认'}</label>`).join('')}</div></div><div class="formrow"><div class="label">图标</div><div style="width:100%"><div class="sample">${draft.mode==='custom'?(draft.img?`<img src="${esc(draft.img)}" alt="自定义图片">`:'请选择组合图片'):logos(tab)}</div>${draft.mode==='custom'?`<p><input aria-label="上传图片" id="upload" type="file" accept="image/jpeg,image/png,image/svg+xml" ${readonly?'disabled':''}></p>`:''}<div class="hint">${tab==='game'?'支持JPG/PNG/SVG；建议尺寸1125×744。':'支持JPG/PNG/SVG；建议尺寸1125×195。'}<br>图片大小不超过2M，默认图为文字标识示意。</div></div></div>${actions('确定')}`;p.querySelectorAll('[name=mode]').forEach(r=>r.onchange=()=>{draft.mode=r.value;mark();renderPanel()});if($('#upload'))$('#upload').onchange=async e=>{const v=++uploadVersion,k=tab;try{const data=await readImage(e.target.files[0]);if(v!==uploadVersion||k!==tab)return;draft.img=data;mark();renderPanel()}catch(err){toast(err.message)}};wireActions()}
else if(tab==='copy'){p.innerHTML=`<h2>首页底部文案</h2><textarea id="copy" rows="14" maxlength="3000" ${readonly?'disabled':''}>${esc(draft)}</textarea><div class="hint">保留换行；纯文本；最多3000字，清空后隐藏文案区域。当前示例不是正式业务文案。</div>${actions()}`;$('#copy').oninput=e=>{draft=e.target.value;mark()};wireActions()}
else if(tab==='media'){p.innerHTML=`<div class="toolbar"><span class="tiny">共 ${state.media.length} 项 · 顺序与客户端一致</span><button class="primary" id="add" ${readonly?'disabled':''}>＋ 新增</button></div><table><thead><tr>${['序号','媒体类型','图标','媒体链接','备注','操作'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${state.media.map((m,i)=>`<tr><td>${i+1}</td><td>${esc(m.type)}</td><td><span class="iconchip">${iconHtml(m)}</span></td><td>${esc(m.url)}</td><td>${esc(m.note)||'—'}</td><td style="white-space:nowrap"><button data-edit="${i}" ${readonly?'disabled':''}>编辑</button><button class="danger" data-delete="${i}" ${readonly?'disabled':''}>删除</button></td></tr>`).join('')||'<tr><td colspan="6">暂无媒体配置，客户端不展示媒体图标。</td></tr>'}</tbody></table><div class="hint">参考图7为Instagram，图8为RTP，差异待确认。此处按图7类型示意；链接#仅展示，不跳转。</div>`;$('#add').onclick=()=>editMedia();p.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editMedia(+b.dataset.edit));p.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const i=+b.dataset.delete;if(confirm('确定删除「'+state.media[i].type+'」？保存后客户端将移除此图标。')){const id=state.media[i].id;save(state.media.filter((_,j)=>j!==i),'删除',id)}})}
else if(tab==='doc'){p.innerHTML=`<p><a href="需求说明.md" download>下载需求说明 ↓</a></p><div class="prd">${renderDoc(PRD)}</div>`}
}

async function readImage(f){if(!f)throw Error('未选择图片');if(!/\.(png|jpe?g|svg)$/i.test(f.name))throw Error('仅支持JPG、PNG、SVG图片');if(f.size>2*1024*1024)throw Error('图片大小不能超过2M');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('图片读取失败'));r.readAsDataURL(f)});await new Promise((resolve,reject)=>{const i=new Image();i.onload=resolve;i.onerror=()=>reject(Error('图片无法读取，请重新上传'));i.src=data});return data}
function editMedia(index){const isEdit=index!==undefined,m=isEdit?structuredClone(state.media[index]):{id:'media-'+Date.now(),type:'',icon:'',url:'',note:''};const d=$('#dialog');let custom=m.icon.startsWith('data:image/')?m.icon:'';d.className='media-modal';d.innerHTML=`<div class="modal-head"><h2>${isEdit?'编辑':'新增'}</h2><button id="mclose" aria-label="关闭">×</button></div><div class="media-fields"><div class="media-row"><label for="mtype">媒体类型：</label><div><input id="mtype" type="text" required maxlength="40" value="${esc(m.type)}" placeholder="请输入"></div></div><div class="media-row"><label for="murl">媒体链接：</label><div><input id="murl" type="text" required value="${esc(m.url)}" placeholder="请输入"></div></div><div class="media-row" style="margin-bottom:0"><label>图标：</label><div class="media-image-line"><div id="mpreview" class="media-image-preview">${custom?`<img src="${esc(custom)}" alt="媒体图标">`:'待上传'}</div><button class="primary" id="mupload">上传图片</button><input id="mfile" aria-label="上传媒体图标" type="file" accept="image/png,image/jpeg,image/svg+xml" hidden></div></div><div class="upload-hint">支持JPG/PNG/SVG格式的图片；建议尺寸：114×114；图片大小不超过2M，必填。</div><div class="media-row"><label for="mnote">备注：</label><div><textarea id="mnote" maxlength="200" placeholder="请输入">${esc(m.note)}</textarea></div></div><div class="error" id="merror" role="alert"></div><div class="actions"><button class="primary" id="msave">确定</button></div></div>`;d.showModal();$('#mclose').onclick=()=>d.close();$('#mupload').onclick=()=>$('#mfile').click();let version=0;$('#mfile').onchange=async e=>{const v=++version,btn=$('#msave');btn.disabled=true;try{const data=await readImage(e.target.files[0]);if(v!==version||!d.open)return;custom=data;$('#mpreview').innerHTML=`<img src="${esc(custom)}" alt="媒体图标">`;$('#merror').textContent=''}catch(err){if(d.open)$('#merror').textContent=err.message}finally{if(v===version)btn.disabled=false}};$('#msave').onclick=()=>{m.type=$('#mtype').value.trim();m.url=$('#murl').value.trim();m.note=$('#mnote').value.trim();m.icon=custom;let error='';if(!m.type)error='请输入媒体类型';else if(state.media.some((x,i)=>i!==index&&x.type.trim().toLowerCase()===m.type.toLowerCase()))error='媒体类型已存在，请勿重复添加';else if(!m.url)error='请输入媒体链接';else if(!custom)error='请上传媒体图标';else if(m.url!=='#'){try{const u=new URL(m.url);if(u.protocol!=='https:'||!u.hostname||u.username||u.password)throw Error()}catch(e){error='链接需为完整HTTPS地址，或填写#仅展示'}}if(error){$('#merror').textContent=error;return}const list=structuredClone(state.media);if(isEdit)list[index]=m;else list.push(m);if(save(list,isEdit?'编辑':'新增',m.id))d.close()}}

window.addEventListener('storage',e=>{if(e.key!==KEY)return;try{const s=JSON.parse(e.newValue);if(!s)return;state=s;if(!dirty){resetDraft();render()}else{updatePreview();toast('已保存配置在其他页面更新；当前草稿保留')}}catch(err){}});resetDraft();render();if(loadError)toast('本地历史数据读取失败，已载入演示默认配置');

function renderDoc(text){const lines=text.split('\n');let out='',rows=[];function flush(){if(!rows.length)return;out+='<table>'+rows.filter(r=>!/^\|[\s|:-]+$/.test(r)).map((r,i)=>'<tr>'+r.split('|').slice(1,-1).map(c=>'<'+(i?'td':'th')+'>'+esc(c.trim()).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>')+'</'+(i?'td':'th')+'>').join('')+'</tr>').join('')+'</table>';rows=[]}for(const l of lines){if(l.startsWith('|')){rows.push(l);continue}flush();if(l.startsWith('## '))out+='<h2>'+esc(l.slice(3))+'</h2>';else if(l.startsWith('# '))out+='<h2>'+esc(l.slice(2))+'</h2>';else if(l.trim())out+='<p>'+esc(l)+'</p>'}flush();return out}

function readSaved(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.game&&x.pay&&typeof x.copy==='string'&&Array.isArray(x.media))state=x;else if(x===null)state=structuredClone(initial)}catch(e){toast('已保存配置读取失败，请刷新后重试')}}
